name: drive_ai
description: "A driving assistant app using AI for traffic light detection and safety features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  provider: ^6.1.1
  permission_handler: ^11.2.0
  google_mlkit_commons: ^0.6.1
  tflite_flutter: ^0.10.4
  opencv_4: ^1.0.0
  image: ^4.1.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/ 