services:
  - type: web
    name: traffic-light-detection
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p src/models
      cp models/best_traffic_small_yolo.pt src/models/
      ls -la src/models/
    startCommand: gunicorn --worker-class eventlet -w 1 --timeout 0 --log-level debug --bind 0.0.0.0:10000 "wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: WEB_CONCURRENCY
        value: "1"
    healthCheckPath: / 